# 숫자야구게임
# 컴퓨터가 랜덤으로 1~9 사이의 임의의 숫자 3개를 생성
# 사용자로부터 1~9 사이의 중복없는 3자리 숫자를 입력받기
# 456 == 임의의 숫자를 3개와 비교 => 3개읭 숫자를 다 맞췄다면 3스트라이크
# 2개만 맞췄다면 0스트라이크 2볼
# q를 입력하기 전까지는 계속 반복
# 3스트라이크 나온다면 반복문 중단

import random
import oracledb
from datetime import datetime
import time

def make_answer():
    # 1~9 중 중복없는 3자리 숫자 생성 후 리턴
    answer = random.sample(range(1, 10), 3)
    return answer

def get_strike_ball(answer,guess) :
    # 답변과 응답 비교 후 strike,ball 값 리턴
    selects = [int(i) for i in guess]
    strike = 0
    ball = 0
    out = 0
    for idx, select in enumerate(selects) :
        if answer[idx] == select :
            strike += 1
        elif select in answer :
            ball += 1
        else : 
            out += 1
    return strike,ball,out

def get_time (start,end) :
    total_time = format(end-start,".2f")
    return total_time

# 오라클 연동
# baseball_records 테이블 생성
# record_id 자동증가, 게임일자, 걸린 시간, 시도횟수
def save_baseball_result (count,et) :
    with oracledb.connect(user='python_user',password="54321",dsn="localhost/xe") as conn :
        with conn.cursor() as cursor :

            try :
                sql = """create table baseball(
                baseball_id NUMBER(8) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, 
                count NUMBER(8),
                record VARCHAR2(20),
                regdate VARCHAR2(20)
                )"""

                cursor.execute(sql)
            except oracledb.DatabaseError as e:
                (error_obj,) = e.args
                if error_obj.code == 955 :
                    print(error_obj.message)
                else:
                    pass

            #insert 작업(기록 삽입)
            
            now = datetime.now()
            nowDatetime = now.strftime("%Y-%m-%d %H:%M:%S")

            sql = "insert into baseball (count,record,regdate) values (:count,:et,:nowDatetime)"
            cursor.execute(sql,(count,et,nowDatetime))
            conn.commit()
    print("기록이 저장되었습니다.")

def base_ball() :
    answer = make_answer()
    count = 0
    start = time.time()
    while True :
        guess = input("숫자 3개 입력(ex:123, 종료 : q)").strip()
        if guess == "q" :
            break

        # 3자리 맞는지, 숫자가 맞는지 확인
        if len(guess) != 3 or not guess.isdigit() :
            print("3자리 숫자로 입력하세요")
            continue

        strike,ball,out = get_strike_ball(answer,guess)
        print(f"{strike} 스트라이크, {ball} 볼, {out} 아웃입니다. ")

        count +=1
        if strike == 3 :
            print("게임 승리 !! 결과 : ",answer)
            end = time.time()
            save_baseball_result(count,get_time(start,end))
            break
        if count == 10 :
            print("게임 패배 : ",answer)
            save_baseball_result(count,get_time(start,end))
            break


# 모듈 테스트
if __name__ == "__main__" :
    base_ball()