# === Todo 관리 ====
# 1. 추가 2. 목록 3. 완료처리 4. 삭제 5. 종료
# 선택 : 1
# 할 일 내용을 입력하세요 : 내용 입력...
# 등록되었습니다.
# 선택 : 2
# 1. [미완료] 강아지 목욕 (2026-08-20 12:38:07)
# 선택 : 3
# 완료 처리할 일 번호를 입력하세요 :
# 완료 처리되었습니다.
# 선택 : 4
# 삭제 처리할 일 번호를 입력하세요 :
# 삭제 처리되었습니다.


# 데이터베이스 테이블 구조
# todo_id 자동증가, pk
# title not null
# is_done number(1) default 0
# created_at 작성일자 sysdate
import oracledb

conn = oracledb.connect(user='python_user',password="54321",dsn="localhost/xe")
cursor = conn.cursor()

# 테이블 생성
try :
    sql = """create table todos(
            todo_id NUMBER(8) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, 
            title VARCHAR2(200) NOT NULL,
            is_done NUMBER(1) default 0,
            created_at DATE DEFAULT SYSDATE
        )"""
    cursor.execute(sql)
    conn.commit()
except oracledb.DatabaseError as e:
    (error_obj,) = e.args
    if error_obj.code == 955 :
        print(error_obj.message)
    else:
        pass

# todo 추가
def add_todo():
    sql = "insert into todos(title) values (:1)"
    title = input("할 일 내용을 입력하세요 : ")

    try : 
        cursor.execute(sql,(title,))
        conn.commit()
        print("등록되었습니다.\n")
    except oracledb.Error as e :
        print("등록 실패.")

def list_todos():
    sql = "select * from todos order by todo_id"
    cursor.execute(sql)
    rows = cursor.fetchall()
    if not rows : 
        print("등록된 할 일 목록이 없습니다.\n")
        return
    print("-" *20)
    for row in rows :
        status = "완료" if row[2] else "미완료"
        print(f"{row[0]}. [{status}] {row[1]} ({row[3]})")
    print("-" *20)

def update_todo():
    list_todos()
    sql = "update todos set is_done = 1 where todo_id = :1 "
    id = int(input("완료 처리할 일 번호를 입력하세요 : "))
    try :
        cursor.execute(sql,(id,))
        conn.commit()
        print("완료 처리되었습니다.\n")
    except oracledb.Error as e :
            print("완료 처리할 대상이 없습니다.")

def delete_todo():
    list_todos()
    sql = "delete from todos where todo_id = :1 "
    id = int(input("삭제 처리할 일 번호를 입력하세요 : "))
    try:
        cursor.execute(sql,(id,))
        conn.commit()
        print("삭제 처리되었습니다.\n")
    except oracledb.Error as e :
        print("삭제 처리할 대상이 없습니다.")


def menu() :
    while True :
        print("===Todo===")
        print("1. 추가 2. 목록 3. 완료처리 4. 삭제 5. 종료")
        choice = input("선택 : ")

        if choice == "1" :
            add_todo()
        elif choice == "2" :
            list_todos()
        elif choice == "3" :
            update_todo()
        elif choice == "4" :
            delete_todo()
        elif choice == "5" :
            print("종료합니다.")
            break
        else :
            print("입력 오류")

if __name__ == "__main__":
    try:
        menu()
    finally :
        cursor.close()
        conn.close()