import random
import time
import oracledb

conn = oracledb.connect(user='python_user',password="54321",dsn="localhost/xe")
cursor = conn.cursor()

sentences = [
    "The quick brown fox jumps over the lazy dog",
    "Python is a powerful programming language",
    "Practice makes perfect every single day",
    "Oracle database stores data reliably",
    "Typing speed imrpoves with daily practice"
]

try :
    # 테이블 생성 :typing record
    sql = """CREATE TABLE typing_records (
        record_id number(10) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        time varchar2(20) not null,
        acc_rate varchar2(20) not null,
        regdate DATE DEFAULT SYSDATE 
    )"""
    cursor.execute(sql)
    conn.commit()
except oracledb.DatabaseError as e:
    (error_obj,) = e.args
    if error_obj.code == 955 :
        print(error_obj.message)
    else:
        pass

# sentences 문장 중 임의의 문장을 출제 후 사용자가 타이핑하는 시간을 잰 후 저장
# 정확도 계산
def calc_acc_rate (origin,sentence) :
    total = len(origin)
    correct = 0
    # for idx, e in enumerate(origin) :
    #     if e == sentence[idx] :
    #         correct += 1
    correct = sum(1 for a,b in zip(origin,sentence) if a == b)
    rate = round((correct/total)*100, 2)
    return rate

def add_typing_result (time,acc_rate) :
    sql = "insert into typing_records (time, acc_rate) values (:1, :2)"
    cursor.execute(sql,(time,acc_rate))
    conn.commit()
    print(f"걸린 시간 : {time}, 정확도율 : {acc_rate}%")
    print("결과가 저장되었습니다.")

def get_time (start,end) :
    total_time = format(end-start,".2f")
    return total_time

# 걸린 시간, 정확도율, 날짜
def typing () :
    origin = random.choice(sentences)
    print("다음 문장 타이핑 ")
    print(origin)
    input("엔터 눌러서 시작 ")
    start = time.time()
    sentence = input("> ")
    end = time.time()
    add_typing_result(get_time(start,end),calc_acc_rate(origin,sentence))

if __name__ == "__main__" :
    try:
        typing()
    finally :
        cursor.close()
        conn.close()